version: "3.8"
services:
  postgres-db:
    container_name: template
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: template
      POSTGRES_PASSWORD: template
      POSTGRES_DB: template
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5420:5432"

volumes:
  postgresql_data:
    driver: local
